on:
  push:
   

  workflow_dispatch:
permissions:
  packages: read
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Setup npmrc"
        working-directory: ./client
        run: echo -e "\n//npm.pkg.github.com/:_authToken-${{ secrets.GITHUB_TOKEN }}" >> ./client/.npmrc

      - name: Test
        working-directory: ./client
        run: ls
      

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: ./client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm install

      - name: Unit tests
        working-directory: ./client
        run: npm run tests

      - name: Docker Compose
        run: docker-compose up client -d \
             -e AUTH0_SECRET=${{ secrets.API_KEY }} \
             -e AUTH0_BASE_URL=${{ secrets.API_KEY }} \
             -e AUTH0_ISSUER_BASE_URL=${{ secrets.API_KEY }} \
             -e AUTH0_CLIENT_ID=${{ secrets.API_KEY }} \
             -e AUTH0_CLIENT_SECRET=${{ secrets.API_KEY }} \
             -e BASE_URL=${{ secrets.API_KEY }} \
             
      - name: Wait for
        run: npx wait-on http://localhost:3000 --verbose --timeout 10000

      


              
        

     

   

  
