on:
  push:

  workflow_dispatch:
permissions:
  packages: read
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  test-and-build-next:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Setup npmrc"
        working-directory: ./client
        run: echo -e "\n//npm.pkg.github.com/:_authToken-${{ secrets.GITHUB_TOKEN }}" >> ./.npmrc

      - name: Log Secrets and Environment Variables
        run: |
          echo "CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}"
          echo "CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}"
          echo "CYPRESS_DOMAIN: ${{ vars.CYPRESS_DOMAIN }}"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: ./client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm install

      - name: Build API client
        working-directory: ./client
        run: npm run build:client

      - name: Unit tests
        working-directory: ./client
        run: npm run test

      - name: Build client
        working-directory: ./client
        run: npm run build

      - name: Docker Compose
        env:
          AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
          AUTH0_BASE_URL: ${{ secrets.AUTH0_BASE_URL }}
          AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: docker-compose up -d client

      - name: Wait for
        run: npx wait-on http://localhost:3000 --verbose --timeout 10000

      - name: Cypress run with env
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./client
        env:
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_DOMAIN: ${{ vars.CYPRESS_DOMAIN }}
