name: Trigger auto deployment for jecfe-next-template-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "client/**"
      - ".github/workflows/jecfe-next-template-container-AutoDeployTrigger-3b23873a-5ece-45be-83ee-5b4e95b5601b.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: "Setup npmrc"
        working-directory: ./client
        run: echo -e "\n//npm.pkg.github.com/:_authToken-${{ secrets.GITHUB_TOKEN }}" >> ./.npmrc

      - name: Install dependencies
        working-directory: ./client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm install

      - name: Build API client
        working-directory: ./client
        run: npm run build:client

      - name: Build client
        working-directory: ./client
        run: npm run build

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.JECFENEXTTEMPLATECONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.JECFENEXTTEMPLATECONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.JECFENEXTTEMPLATECONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/client
          registryUrl: jecfeacr.azurecr.io
          registryUsername: ${{ secrets.JECFENEXTTEMPLATECONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.JECFENEXTTEMPLATECONTAINER_REGISTRY_PASSWORD }}
          containerAppName: jecfe-next-template-container
          resourceGroup: rg-shared-resources
          imageToBuild: jecfeacr.azurecr.io/jecfe-next-template-container:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_
